name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_SECRET_KEY: ${{ secrets.OPENWEATHER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use API key
        run: |
          echo ${{ secrets.OPENWEATHER }}